### ISSUE TITLE
Programming icons

### ISSUE THREAD

**Issue by sid-r-singh** [andyruwruw/andyruwruw#5]
Hey, how did you get those programming logos along with shadow? Don't say u edited all the pics & put the final pic here 😄

**Comment by andyruwruw** [comment]
It's not a pretty way, the images are generated when needed.

The icons themselves are SVGs, but the data are stored as typescript arrays, [you can see one here](https://github.com/andyruwruw/andyruwruw/blob/master/src/components/skills/config/vue.ts).

That array is then passed to a [react component that generates the SVG element](https://github.com/andyruwruw/andyruwruw/blob/master/src/components/skills/Icon.tsx).

A collection of those SVG are then passed to another[ react component which shows the full list](https://github.com/andyruwruw/andyruwruw/blob/master/src/components/skills/Skills.tsx), and adds the shadow + box around the SVGs. 

And all of that is served by an [API endpoint](https://github.com/andyruwruw/andyruwruw/blob/master/api/skills.ts) that the markdown calls.

If you really want just the photos, you can write them up by hand as a `.svg` file and place them in your README.md.

I had plans to make a public API for all these components, I'll make it known when that's available :)

**Comment by GalexY727** [comment]
I love doing `<code><img width="" src=""></code>`, it makes a nice little shelf and it is very lightweight-- I would consider it!
Example:
<code><img width="4%" src="https://www.vectorlogo.zone/logos/java/java-icon.svg"></code>
