### ISSUE TITLE
environment variables

### ISSUE THREAD

**Issue by Nithin552** [andyruwruw/andyruwruw#8]
can you mention the environment variables of spotify now-playing for deploying in vercel

**Comment by andyruwruw** [comment]
Sorry I'm so late with the reply, [it's here](https://github.com/andyruwruw/andyruwruw/blob/master/HOW-IT-WORKS.md#using-the-same-apis)!

```
SPOTIFY_CLIENT_ID=
SPOTIFY_CLIENT_SECRET=
SPOTIFY_REFRESH_TOKEN=
```

You'll have to visit [Spotify Developer Dashboard](https://developer.spotify.com/dashboard/) to get the first two values. The third requires you authenticated your app with your account.

I'll update [the guide](https://github.com/andyruwruw/andyruwruw/blob/master/HOW-IT-WORKS.md#using-the-same-apis) on info on how to get that refresh token.

Make sure that the refresh token you give it is authenticated for the following scopes:
- `user-read-currently-playing` or `user-read-playback-state` (For Now Playing)
- `user-read-recently-played` (For Last Played)
-  `user-top-read` (For Top Played)

**Comment by Nithin552** [comment]
yeah thanks but sadly my refresh token revoked, i accidentally removed my app access now im unable to track my recently played list in README..is there any way to geneate new refresh token using SPOTIFY_CLIENT_ID,SPOTIFY_CLIENT_SECRET using same credentials??

**Comment by Nithin552** [comment]
i got my new refresh token will try api
